---
AWSTemplateFormatVersion: '2010-09-09'
Description: Example for custom metrics
Parameters:
  Owner:
    Description: Enter Team or Individual Name Responsible for the Stack.
    Type: String
    Default: FirstName LastName
  Project:
    Description: Enter Project Name.
    Type: String
    Default: Infrastructure Stack Creation
  Environment:
    Description: Select Environment to run the stack
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - qa
    - pre
    - pro
    ConstraintDescription: Must be one of dev, qa, pre, pro.
  Version:
    Description: Project Version
    Type: String
    Default: 1.0.0
  DeleteAfter:
    Description: Enter Date (MM/DD/YYYY). It's Ok to Delete the Stack or 'Never' if
      meant to be persistent.
    Type: String
    Default: 00/00/201x
  CustomAlarmName:
    Description: Custom alarm name
    Type: String
    Default: CustomName
  AlarmEventType:
    Description: Alarm event type
    Type: String
    Default: generic
Mappings:
  EnvironmentParams:
    common:
      ConfigBucketName: projectFOO-infra
    dev:
      ConfigBucketName: projectFOO-infra-dev
    pre:
      ConfigBucketName: projectFOO-infra-pre
    pro:
      ConfigBucketName: projectFOO-infra-pro
Resources:
<% for(var i in alarmTypes) { -%>
<%   include ./partials/alarm-stack.yml -%>
<% } -%>
Outputs:
  Owner:
    Description: Team or Individual that Owns this Formation.
    Value:
      Ref: Owner
  Project:
    Description: The project name
    Value:
      Ref: Project
  Environment:
    Description: Environment
    Value:
      Ref: Environment
  DeleteAfter:
    Description: It is ok to delete this Formation after this date
    Value:
      Ref: DeleteAfter
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Ownership
      Parameters:
      - Owner
      - Project
      - Environment
      - Version
      - DeleteAfter

