---
AWSTemplateFormatVersion: '2010-09-09'
Description: 100 Networking
Parameters:
  # Common information for all resources.
  Owner:
    Description: Enter Team or Individual Name Responsible for the Stack.
    Type: String
    Default: FirstName LastName
  Project:
    Description: Enter Project Name.
    Type: String
    Default: Infrastructure Stack Creation
  Role:
    Description: Role Name
    Type: String
    Default: infra
  Environment:
    Description: Select Environment to run the stack
    Type: String
    Default: dev
    AllowedValues:
    - pilot
    - dev
    - pre
    - pro
    ConstraintDescription: Must be one of dev, pre, pro.
  Version:
    Description: Project Version
    Type: String
    Default: 1.0.0
  DeleteAfter:
    Description: Enter Date (MM/DD/YYYY). It's Ok to Delete the Stack or 'Never' if
      meant to be persistent.
    Type: String
    Default: 00/00/201x
  # VPC configuration.
  VPCSubnetCidrBlock:
    Description: Enter VPC CIDR Block. (i.e. 10.0.0.0/16 = 10.0.0.0-10.0.255.255 =
      256 Subnets - 65534 hosts)
    Type: String
    Default: 10.0.0.0/16
    MinLength: '10'
    MaxLength: '18'
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  AvailabilityZone1:
    Description: Enter Availability Zone 1 for Public and Private Subnets to use.
    Type: String
    Default: a
    AllowedValues:
    - a
    - b
    - c
    - d
    - e
    - f
  AvailabilityZone2:
    Description: Enter Availability Zone 1 for Public and Private Subnets to use.
    Type: String
    Default: b
    AllowedValues:
    - a
    - b
    - c
    - d
    - e
    - f
  AvailabilityZone3:
    Description: Enter Availability Zone 1 for Public and Private Subnets to use.
    Type: String
    Default: c
    AllowedValues:
    - a
    - b
    - c
    - d
    - e
    - f
  PublicSubnetCidrBlock1:
    Description: Enter Public Subnet 1 CIDR Block.
    Type: String
    Default: 10.0.1.0/24
    MinLength: '10'
    MaxLength: '18'
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  PublicSubnetCidrBlock2:
    Description: Enter Public Subnet 2 CIDR Block.
    Type: String
    Default: 10.0.2.0/24
    MinLength: '10'
    MaxLength: '18'
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  PublicSubnetCidrBlock3:
    Description: Enter Public Subnet 3 CIDR Block.
    Type: String
    Default: 10.0.3.0/24
    MinLength: '10'
    MaxLength: '18'
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  PrivateSubnetCidrBlock1:
    Description: Enter Private Subnet 1 CIDR Block.
    Type: String
    Default: 10.0.4.0/24
    MinLength: '10'
    MaxLength: '18'
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  PrivateSubnetCidrBlock2:
    Description: Enter Private Subnet 2 CIDR Block.
    Type: String
    Default: 10.0.5.0/24
    MinLength: '10'
    MaxLength: '18'
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  PrivateSubnetCidrBlock3:
    Description: Enter Private Subnet 3 CIDR Block.
    Type: String
    Default: 10.0.6.0/24
    MinLength: '10'
    MaxLength: '18'
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  RemoteAccessNetwork:
    Description: Source Network IP CIDR Block such as an Office that can access instances
      say over VPN. (i.e. 192.168.100.0/24)
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 192.168.100.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
  # NatGateway configuration
  SetupNatGateway:
    Description: Setup Nat Gateway?
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
Conditions:
  ConfigNatGateway:
    Fn::Equals:
    - Ref: SetupNatGateway
    - 'true'
Mappings:
  EnvironmentParams:
    common:
      ConfigBucketName: projectfoo-infra
    dev:
      ConfigBucketName: projectfoo-infra-dev
    pre:
      ConfigBucketName: projectfoo-infra-pre
    pro:
      ConfigBucketName: projectfoo-infra-pro
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Join:
        - ''
        - - https://s3.amazonaws.com/
          - Fn::FindInMap:
            - EnvironmentParams
            - Ref: Environment
            - ConfigBucketName
          - "/cloudformation/templates/network/vpc-3az.yaml"
      TimeoutInMinutes: '15'
      Parameters:
        Owner:
          Ref: Owner
        Project:
          Ref: Project
        Environment:
          Ref: Environment
        DeleteAfter:
          Ref: DeleteAfter
        VPCSubnetCidrBlock:
          Ref: VPCSubnetCidrBlock
        AvailabilityZone1:
          Ref: AvailabilityZone1
        AvailabilityZone2:
          Ref: AvailabilityZone2
        AvailabilityZone3:
          Ref: AvailabilityZone3
        PublicSubnetCidrBlock1:
          Ref: PublicSubnetCidrBlock1
        PublicSubnetCidrBlock2:
          Ref: PublicSubnetCidrBlock2
        PublicSubnetCidrBlock3:
          Ref: PublicSubnetCidrBlock3
        PrivateSubnetCidrBlock1:
          Ref: PrivateSubnetCidrBlock1
        PrivateSubnetCidrBlock2:
          Ref: PrivateSubnetCidrBlock2
        PrivateSubnetCidrBlock3:
          Ref: PrivateSubnetCidrBlock3
        RemoteAccessNetwork:
          Ref: RemoteAccessNetwork
  NAT:
    Condition: ConfigNatGateway
    DependsOn:
    - VPC
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Join:
        - ''
        - - https://s3.amazonaws.com/
          - Fn::FindInMap:
            - EnvironmentParams
            - Ref: Environment
            - ConfigBucketName
          - "/cloudformation/templates/network/nat-gateway.yaml"
      TimeoutInMinutes: '15'
      Parameters:
        Owner:
          Ref: Owner
        Project:
          Ref: Project
        Environment:
          Ref: Environment
        DeleteAfter:
          Ref: DeleteAfter
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VPC
        PublicSubnet:
          Fn::GetAtt:
          - VPC
          - Outputs.PublicSubnet1
        PrivateRouteTable:
          Fn::GetAtt:
          - VPC
          - Outputs.PrivateRouteTable
Outputs:
  # Common information for all resources.
  Owner:
    Description: Responsible of the stack creation.
    Value:
      Ref: Owner
  Project:
    Description: Project name.
    Value:
      Ref: Project
  Environment:
    Description: Environment stage.
    Value:
      Ref: Environment
  DeleteAfter:
    Description: Date when the resource will automatically deleted.
    Value:
      Ref: DeleteAfter
  # VPC configuration.
  VPC:
    Description: Created VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.VPC
    Export:
          Name: !Sub "${AWS::StackName}-VPC"
  VPCCIDR:
    Description: VPC Subnet CIDR Block
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.VPCCIDR
    Export:
          Name: !Sub "${AWS::StackName}-VPCCIDRIP"
  VPCe:
    Description: Created VPC Endpoint
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.VPCe
  PublicRouteTable:
    Description: Public Route Table Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PublicRouteTable
  PrivateRouteTable:
    Description: Private Route Table Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PrivateRouteTable
  PublicNetworkAcl:
    Description: Public Network ACL Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PublicNetworkAcl
  PrivateNetworkAcl:
    Description: Private Netowrk ACL Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PrivateNetworkAcl
  PublicSubnet1:
    Description: Public Subnet 1 Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PublicSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet1"
  PublicSubnet2:
    Description: Public Subnet 2 Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PublicSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet2"
  PublicSubnet3:
    Description: Public Subnet 3 Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PublicSubnet3
    Export:
      Name: !Sub "${AWS::StackName}-PublicSubnet3"
  PrivateSubnet1:
    Description: Private Subnet 1 Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PrivateSubnet1
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet1"
  PrivateSubnet2:
    Description: Private Subnet 1 Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PrivateSubnet2
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet2"
  PrivateSubnet3:
    Description: Private Subnet 1 Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PrivateSubnet3
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSubnet3"
  AvailabilityZone1:
    Description: Private Subnet IDs Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.AvailabilityZone1
  AvailabilityZone2:
    Description: Private Subnet IDs Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.AvailabilityZone2
  AvailabilityZone3:
    Description: Private Subnet IDs Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.AvailabilityZone3
  PublicSubnetCidr1:
    Description: Public Subnet IDs Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PublicSubnetCidr1
  PublicSubnetCidr2:
    Description: Public Subnet IDs Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PublicSubnetCidr2
  PublicSubnetCidr3:
    Description: Public Subnet IDs Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PublicSubnetCidr3
  PrivateSubnetCidr1:
    Description: Private Subnet IDs Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PrivateSubnetCidr1
  PrivateSubnetCidr2:
    Description: Private Subnet IDs Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PrivateSubnetCidr2
  PrivateSubnetCidr3:
    Description: Private Subnet IDs Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.PrivateSubnetCidr3
  InternetGateway:
    Description: Internet Gateway Created for VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.InternetGateway
  InternalAccessSecurityGroup:
    Description: Instance to Instance Access within VPC
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.InternalAccessSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-InternalAccessSecurityGroup"
  RemoteAccessSecurityGroup:
    Description: Remote Network or IP that can Access the instances of VPN or Direct Connect.
    Value:
      Fn::GetAtt:
      - VPC
      - Outputs.RemoteAccessSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-RemoteAccessSecurityGroup"
  NatEIP:
    Description: NAT IP Address
    Value:
      Fn::GetAtt:
      - NAT
      - Outputs.NatEIP
