---
AWSTemplateFormatVersion: '2010-09-09'
Description: '002 Storage: Bucket for storing Logs'
Parameters:
  Owner:
    Description: Enter Team or Individual Name Responsible for the Stack.
    Type: String
    Default: FirstName LastName
  Project:
    Description: Enter Project Name.
    Type: String
    Default: S3 Logging Bucket
  Role:
    Description: Role Name.
    Type: String
    Default: storage
  Environment:
    Description: Select Environment to run the stack
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - qa
    - pre
    - pro
    ConstraintDescription: Must be one of dev, qa, pre, pro.
  DeleteAfter:
    Description: Enter Date (MM/DD/YYYY). It's Ok to Delete the Stack or 'Never' if
      meant to be persistent.
    Type: String
    Default: 00/00/201x
  BucketName:
    Description: The bucket name.
    Type: String
    Default: deploy
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName:
        Fn::Join:
        - "-"
        - - Ref: Project
          - Ref: BucketName
          - Ref: Environment
      LifecycleConfiguration:
        Rules:
        - Transition:
            StorageClass: Glacier
            TransitionInDays: '90'
          ExpirationInDays: '1825'
          Status: Enabled
          Prefix: glacier
          Id: GlacierRule
      VersioningConfiguration:
        Status: Enabled
      Tags:
      - Key: Name
        Value:
          Fn::Join:
          - "-"
          - - Ref: Project
            - Ref: BucketName
            - Ref: Environment
      - Key: Owner
        Value:
          Ref: Owner
      - Key: Project
        Value:
          Ref: Project
      - Key: Environment
        Value:
          Ref: Environment
      - Key: DeleteAfter
        Value:
          Ref: DeleteAfter
  RoleLoggingBucketWriteAccess:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      RoleName:
        Fn::Join:
        - "-"
        - - Ref: Project
          - loggingbucket-role
          - Ref: Environment
  PolicyLoggingBucketWriteAccess:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LoggingBucketWriteAccessPolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - s3:GetBucketLocation
          - s3:ListAllMyBuckets
          Resource: arn:aws:s3:::*
        - Effect: Allow
          Action:
          - s3:*
          Resource:
          - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Fn::Join:
                - "-"
                - - Ref: Project
                  - logging
                  - Ref: Environment
          - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Fn::Join:
                - "-"
                - - Ref: Project
                  - logging
                  - Ref: Environment
              - "/*"
      Roles:
      - Ref: RoleLoggingBucketWriteAccess
Outputs:
  BucketName:
    Value:
      Ref: S3Bucket
    Description: Name of S3 bucket

